version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network  # Connects backend to custom network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network  # Connects frontend to custom network

networks:
  app-network:
    driver: bridge  # Creates a custom bridge network