name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker images
        run: |
          docker build -t saulgoodman13/hls-transcoder-backend ./backend
          docker build -t saulgoodman13/hls-transcoder-frontend ./frontend

      - name: Publish to DockerHub
        run: |
          docker push saulgoodman13/hls-transcoder-backend:latest
          docker push saulgoodman13/hls-transcoder-frontend:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull images from DockerHub
        run: |
          docker pull saulgoodman13/hls-transcoder-backend:latest
          docker pull saulgoodman13/hls-transcoder-frontend:latest

      - name: Delete old containers
        run: |
          docker rm -f hls-transcoder-backend-container || true
          docker rm -f hls-transcoder-frontend-container || true

      - name: Create .env file
        run: |
          echo "PORT=5000" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env
          echo "S3_BUCKET_NAME_PROD=${{ secrets.S3_BUCKET_NAME_PROD }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "SQS_QUEUE_URL=${{ secrets.SQS_QUEUE_URL }}" >> .env
          echo "SQS_PROCESSED_QUEUE_URL=${{ secrets.SQS_PROCESSED_QUEUE_URL }}" >> .env
          echo "CLUSTER_ARN=${{ secrets.CLUSTER_ARN }}" >> .env
          echo "TASK_DEFINITION_ARN=${{ secrets.TASK_DEFINITION_ARN }}" >> .env

      - name: Deploy with Docker Compose
        run: |
          cd /path/to/your/project/on/ec2
          docker-compose --env-file .env down || true
          docker-compose --env-file .env up -d
