name: Deploy to EC2

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout source
              uses: actions/checkout@v4

            - name: Login to dockerhub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build backend image
              run: |
                  docker build -t saulgoodman13/hls-transcoder-backend:latest ./backend
                  docker push saulgoodman13/hls-transcoder-backend:latest

            - name: Build frontend image
              run: |
                  docker build -t saulgoodman13/hls-transcoder-frontend:latest ./frontend
                  docker push saulgoodman13/hls-transcoder-frontend:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            # Step to pull the backend image
            - name: Pull backend image from Docker Hub
              run: docker pull saulgoodman13/hls-transcoder-backend:latest

            # Step to pull the frontend image
            - name: Pull frontend image from Docker Hub
              run: docker pull saulgoodman13/hls-transcoder-frontend:latest

            # Step to run the backend container
            - name: Run backend container
              run: |
                  docker run -d -p 5000:5000 \
                    --name hls-transcoder-backend-container \
                    -e PORT='5000' \
                    -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
                    -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
                    -e S3_BUCKET_NAME='${{ secrets.S3_BUCKET_NAME }}' \
                    -e S3_BUCKET_NAME_PROD='${{ secrets.S3_BUCKET_NAME_PROD }}' \
                    -e AWS_REGION='${{ secrets.AWS_REGION }}' \
                    -e SQS_QUEUE_URL='${{ secrets.SQS_QUEUE_URL }}' \
                    -e SQS_PROCESSED_QUEUE_URL='${{ secrets.SQS_PROCESSED_QUEUE_URL }}' \
                    -e CLUSTER_ARN='${{ secrets.CLUSTER_ARN }}' \
                    -e TASK_DEFINITION_ARN='${{ secrets.TASK_DEFINITION_ARN }}' \
                    saulgoodman13/hls-transcoder-backend:latest

            # Step to run the frontend container
            - name: Run frontend container
              run: |
                  docker run -d -p 80:80 \
                    --name hls-transcoder-frontend-container \
                    -e VITE_BACKEND_URL='http://13.233.102.84:5000' \
                    saulgoodman13/hls-transcoder-frontend:latest
